[build]
  # Build command (not needed for static site)
  command = ""
  
  # Publish directory
  publish = "."

[build.environment]
  # Node.js version for build environment
  NODE_VERSION = "18"

# Redirect rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/Pictures/*"
  [headers.values]
    Cache-Control = "max-age=31536000, public, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "max-age=31536000, public, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "max-age=31536000, public, immutable"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "max-age=0, no-cache, no-store, must-revalidate"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "max-age=3600, public, must-revalidate"

# Edge functions (optional)
# [[edge_functions]]
#   function = "analytics"
#   path = "/api/*"
